### ISSUE TITLE
Windows 10 "on" command issue

### ISSUE THREAD

**Issue by Jizzay1** [bp2008/MonitorControl#1]
Windows 10 professional
Dell Inspiron 3477 all in one PC

Http "off" command and other commands work

When screen is "off", http command for "on" will result in screen turning on for 1 second then back off, and screen stays off. Happens consistently even after PC reboot.

**Comment by bp2008** [comment]
Hmm.  I haven't used the "on" functionality in quite some time, but that does ring a bell.  I am pretty sure that is a Windows bug.  I wonder if some emulated mouse movement would help convince Windows that the screen should actually stay on.

**Comment by Jizzay1** [comment]
Darn. I've got a really neat use case. Using a motion sensor connected to Home Assistant on a raspberry Pi, I want to to wake and sleep the screen of a wall mounted windows touchscreen that runs a home assistant dashboard.

Anything you think the app can do to help the screen turn on or dead end?

**Comment by bp2008** [comment]
I found a solution that works on my machine.  Please try [version 1.3](https://github.com/bp2008/MonitorControl/releases).

**Comment by bp2008** [comment]
Some of the mouse movement APIs available in Windows do not wake the screen, but I found one that does (at least on this machine!).

I have wanted to do similar with a wall mounted panel before, but I don't have any (yet) where I am living right now!  Another option is to do motion detection with a webcam, but a PIR motion sensor should be much more efficient.

**Comment by Jizzay1** [comment]
Omg that looks to have worked! You're awesome! Can I send you a beer or a coffee. Thanks for your work.

**Comment by bp2008** [comment]
No need ;)  But if you insist, I do have a [paypal acct](https://www.paypal.com/paypalme/bp2008).
